--
-- PostgreSQL database dump
--

\restrict sdYNH80jOtaqvZ1FfU11T63Ny1lEEwBlhtlxMygCac2EPgXmh2Oj6vmCeljZQY3

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: tarea; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tarea (
    id bigint NOT NULL,
    descripcion character varying(255),
    estado character varying(255) NOT NULL,
    fechavencimiento date,
    titulo character varying(255) NOT NULL
);


--
-- Name: tarea_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tarea ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tarea_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tarea tarea_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tarea
    ADD CONSTRAINT tarea_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

\unrestrict sdYNH80jOtaqvZ1FfU11T63Ny1lEEwBlhtlxMygCac2EPgXmh2Oj6vmCeljZQY3

